version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      NODE_ENV: production
      BOT_TOKEN: ${BOT_TOKEN}
    env_file:
      - ./.env
    command: ["./wait-for-it.sh", "db:5432", "--", "npm", "start"]
    volumes:
      - ./wait-for-it.sh:/app/wait-for-it.sh
    # restart: always

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    # restart: always

volumes:
  pgdata:
