version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./telegraf-predictor.sqlite:/usr/src/app/telegraf-predictor.sqlite
      - ./telegraf-sessions.sqlite:/usr/src/app/telegraf-sessions.sqlite
    environment:
      NODE_ENV: production
    env_file:
      - ./.env
    restart: always  # Политика автоматического перезапуска
